# 错误处理
我们在编写程序时，为了加强程序的健壮性，往往会考虑到对程序中可能出现的错误和异常进行处理。
## 错误处理的方式
举例：
```go
package main

import (
    "fmt"
    "io/ioutil"
)

func main() {
    f, err := ioutil.ReadFile("test.txt")
    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println(f)
    }
}
```
ReadFile方法中包含两个返回值，类型分别为[]byte和error。我们通过error类型的返回值来判断方法调用是否产生错误，若值为nil，则调用为产生错误。
## 自定义错误
### 错误类型
Go语言的error类型实际上是一个接口，定义如下：
```go
type error interface {
    Error() string
}
```
error接口包含Error方法，用来返回一个字符串。换言之，所有符合Error()string格式的方法，都能实现错误的借口。
### 创建错误
Go语言标准库中的errors包可以用来创建错误，自定义错误内容，格式如下：
```go
err := errors.New("this is a error")
```
举例：
```go
package main

import (
    "fmt"
    "errors"
)

func main() {
    err := errors.New("this is a error")
    var err2 error
    fmt.Println(err.Error())
    fmt.Println("err2")
}
```
结果：
```go
this is a error
<nil>
```
### 自定义错误
举例：
```go
package main

import (
    "fmt"
    "runtime"
)

func main() {
    if _,_,line,ok := runtime.Caller(0);ok == true {
        err := fmt.Errorf("***Line  %d  error***",line)
        fmt.Println(err.Error())
    }
}
```
结果：
```go
*** Line  9  error***
```
## Go语言宕机
一般而言，只有当程序发生不可逆的错误时，才会使用panic方法来触发宕机。panic方法是Go语言的一个内置函数，使用panic方法后，程序的执行将会直接中断。

举例：
```go
package main

import (
    "fmt"
)

func main() {
    panic("Serious bug")
    fmt.Println("Invalid code")
}
```
结果：
```go
panic: Serioud bug
```
调用panic方法后，之后的代码都是无效代码，因为程序会直接退出。
如果遇到以下情形，可以调用panic方法来提出程序：
* 程序处于失控状态且无法恢复，继续执行将会影响其他正常程序，引发操作系统异常甚至是死机。
* 发生不可预知的错误。

### recover捕获宕机
Go语言通过内置函数recover来捕获宕机。
在使用panic方法触发宕机后，且在退出当前函数前，会调用延迟函数执行语句defer，代码示例：
```go
package main

import "fmt"

func protect() {
    defer func() {
        fmt.Println("func protect exit")
    }()
    panic ("Serious bug")
}

func main() {
    defer func() {
        fmt.Println("func main ecit ")
    }()
    protect()
    fmt.Println("Invaild code")
}
```

执行结果：
```go
func protect exit 
func main exit
panic：Serious bug
```

